language: node_js
node_js:
  - "12"
  - "10"
  - "8"
  - "6"
before_install:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
addons:
  firefox: latest
  chrome: stable
after_success:
  - npm run build
  - npm run test1
